version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: ndk-{{ checksum "scripts/install_ndk.sh" }}
      - run:
          name: Install NDK
          command: ./scripts/install_ndk.sh
      - save_cache:
          paths:
            - ~/ndkdhry-ndk
          key: ndk-{{ checksum "scripts/install_ndk.sh" }}
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: . scripts/sdkpath.sh && ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build Release
          command: . scripts/sdkpath.sh && ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: release

